-- Full A1-C2 curriculum support. This migration is deliberately additive:
-- legacy lessons, attempts, progress and access records are retained.

alter table public.levels drop constraint if exists levels_code_check;
alter table public.levels add constraint levels_code_check
  check (code in ('A1', 'A2', 'B1', 'B2', 'C1', 'C2'));

insert into public.levels (code, title, position) values
  ('B1', 'Independência em inglês', 3),
  ('B2', 'Comunicação com confiança', 4),
  ('C1', 'Domínio avançado', 5),
  ('C2', 'Precisão e nuance', 6)
on conflict (code) do update set title = excluded.title, position = excluded.position;

alter table public.modules
  add column if not exists external_id text,
  add column if not exists theme text,
  add column if not exists description text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;
create unique index if not exists modules_external_id_idx
  on public.modules (external_id) where external_id is not null;

alter table public.lessons
  add column if not exists external_id text,
  add column if not exists global_order integer,
  add column if not exists level_lesson_number integer,
  add column if not exists module_lesson_number integer,
  add column if not exists lesson_role text,
  add column if not exists can_do jsonb not null default '[]'::jsonb,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists course_version text,
  add column if not exists is_legacy boolean not null default true;
create unique index if not exists lessons_external_id_idx
  on public.lessons (external_id) where external_id is not null;
create unique index if not exists lessons_global_order_idx
  on public.lessons (global_order) where global_order is not null and not is_legacy;
create index if not exists lessons_curriculum_catalog_idx
  on public.lessons (published, global_order) where not is_legacy;

alter table public.lesson_blocks drop constraint if exists lesson_blocks_block_type_check;
alter table public.lesson_blocks add constraint lesson_blocks_block_type_check check (block_type in (
  'text', 'overview', 'can_do', 'vocabulary', 'grammar', 'language_focus',
  'example', 'examples', 'multiple_choice', 'fill_blank', 'reorder_words',
  'true_false', 'listening', 'pronunciation', 'speaking', 'reading', 'writing',
  'practice', 'production', 'assessment', 'visual', 'checkpoint',
  'language_analysis', 'input_response', 'guided_production',
  'contrast_explanation', 'matching', 'notice', 'controlled_gap',
  'guided_output', 'register_edit', 'cross_text', 'synthesis_microtask'
));
alter table public.lesson_blocks
  add column if not exists external_id text,
  add column if not exists audio_required boolean not null default false,
  add column if not exists audio_role text,
  add column if not exists transcript text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;
create unique index if not exists lesson_blocks_external_id_idx
  on public.lesson_blocks (external_id) where external_id is not null;
create index if not exists lesson_blocks_audio_required_idx
  on public.lesson_blocks (lesson_id, audio_status) where audio_required;

alter table public.exercises
  add column if not exists external_id text,
  add column if not exists grading_mode text not null default 'automatic',
  add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.exercises drop constraint if exists exercises_grading_mode_check;
alter table public.exercises add constraint exercises_grading_mode_check
  check (grading_mode in ('automatic', 'subjective'));
create unique index if not exists exercises_external_id_idx
  on public.exercises (external_id) where external_id is not null;

alter table public.exercise_attempts alter column correct drop not null;
alter table public.exercise_attempts
  add column if not exists submission_status text not null default 'graded',
  add column if not exists feedback jsonb not null default '{}'::jsonb;
alter table public.exercise_attempts drop constraint if exists exercise_attempts_submission_status_check;
alter table public.exercise_attempts add constraint exercise_attempts_submission_status_check
  check (submission_status in ('submitted', 'graded'));

alter table public.profiles
  add column if not exists course_completed_at timestamptz;

create table if not exists private.answer_keys (
  external_id text primary key,
  expected_answer jsonb,
  accepted_answers jsonb,
  model_answer text,
  rationale text,
  rubric jsonb,
  source_metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
revoke all on private.answer_keys from public, anon, authenticated;
grant all on private.answer_keys to service_role;

create table if not exists public.lesson_assets (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  lesson_id bigint references public.lessons(id) on delete cascade,
  grammar_clinic_external_id text,
  storage_path text not null unique,
  media_type text not null default 'image/svg+xml',
  alt_text text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check ((lesson_id is not null) <> (grammar_clinic_external_id is not null))
);

create table if not exists public.grammar_clinics (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  level_code text not null references public.levels(code) on update cascade on delete restrict,
  title text not null,
  focus jsonb not null default '[]'::jsonb,
  why_text text,
  examples jsonb not null default '[]'::jsonb,
  recycle_in jsonb not null default '[]'::jsonb,
  visual_external_id text,
  position integer not null,
  published boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create unique index if not exists grammar_clinics_order_idx
  on public.grammar_clinics (level_code, position);

create table if not exists public.grammar_clinic_exercises (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.grammar_clinics(id) on delete cascade,
  external_id text not null unique,
  exercise_type text not null,
  position integer not null check (position > 0),
  prompt text not null,
  instruction text,
  content jsonb not null default '{}'::jsonb,
  grading_mode text not null default 'subjective' check (grading_mode in ('automatic', 'subjective')),
  unique (clinic_id, position)
);

create table if not exists public.grammar_clinic_submissions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  exercise_id bigint not null references public.grammar_clinic_exercises(id) on delete cascade,
  answer jsonb not null,
  submitted_at timestamptz not null default now()
);
create index if not exists clinic_submissions_student_idx
  on public.grammar_clinic_submissions (student_id, submitted_at desc);

create table if not exists public.assessment_rubrics (
  level_code text primary key references public.levels(code) on update cascade on delete restrict,
  rubric jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.review_schedule (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  review_offset_days integer not null check (review_offset_days in (1, 3, 7, 21)),
  due_at timestamptz not null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (student_id, lesson_id, review_offset_days)
);
create index if not exists review_schedule_due_idx
  on public.review_schedule (student_id, completed_at, due_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lesson-visuals', 'lesson-visuals', false, 1048576, array['image/svg+xml'])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.lesson_assets enable row level security;
alter table public.grammar_clinics enable row level security;
alter table public.grammar_clinic_exercises enable row level security;
alter table public.grammar_clinic_submissions enable row level security;
alter table public.assessment_rubrics enable row level security;
alter table public.review_schedule enable row level security;

drop policy if exists "accessible lesson assets" on public.lesson_assets;
create policy "accessible lesson assets" on public.lesson_assets for select to authenticated
using (
  (lesson_id is not null and private.can_access_lesson(lesson_id))
  or (grammar_clinic_external_id is not null and exists (
    select 1 from public.grammar_clinics c
    where c.external_id = grammar_clinic_external_id and c.published
  ))
);
drop policy if exists "authenticated read clinics" on public.grammar_clinics;
create policy "authenticated read clinics" on public.grammar_clinics for select to authenticated using (published);
drop policy if exists "authenticated read clinic exercises" on public.grammar_clinic_exercises;
create policy "authenticated read clinic exercises" on public.grammar_clinic_exercises for select to authenticated
using (exists (select 1 from public.grammar_clinics c where c.id = clinic_id and c.published));
drop policy if exists "clinic submissions read self or admin" on public.grammar_clinic_submissions;
create policy "clinic submissions read self or admin" on public.grammar_clinic_submissions for select to authenticated
using ((select auth.uid()) = student_id or private.is_admin());
drop policy if exists "authenticated read rubrics" on public.assessment_rubrics;
create policy "authenticated read rubrics" on public.assessment_rubrics for select to authenticated using (true);
drop policy if exists "review schedule read self or admin" on public.review_schedule;
create policy "review schedule read self or admin" on public.review_schedule for select to authenticated
using ((select auth.uid()) = student_id or private.is_admin());

revoke all on public.lesson_assets, public.grammar_clinics, public.grammar_clinic_exercises,
  public.grammar_clinic_submissions, public.assessment_rubrics, public.review_schedule from anon, authenticated;
grant select on public.lesson_assets, public.grammar_clinics, public.grammar_clinic_exercises,
  public.grammar_clinic_submissions, public.assessment_rubrics, public.review_schedule to authenticated;
grant all on public.lesson_assets, public.grammar_clinics, public.grammar_clinic_exercises,
  public.grammar_clinic_submissions, public.assessment_rubrics, public.review_schedule to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  base_username text;
  final_username text;
begin
  base_username := lower(regexp_replace(
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(coalesce(new.email, 'student'), '@', 1)),
    '[^a-z0-9._-]', '', 'g'
  ));
  if length(base_username) < 3 then base_username := 'student'; end if;
  final_username := left(base_username, 31);
  if exists (select 1 from public.profiles where lower(username) = lower(final_username)) then
    final_username := left(base_username, 22) || '-' || left(new.id::text, 8);
  end if;

  insert into public.profiles (id, username, display_name, role, current_level_code)
  values (
    new.id, final_username,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), initcap(replace(final_username, '.', ' '))),
    'student', 'A1'
  );

  insert into public.student_lesson_access (student_id, lesson_id, unlocked)
  select new.id, l.id, true from public.lessons l
  where l.published and not l.is_legacy
  order by l.global_order nulls last limit 1;
  return new;
end;
$$;

drop function if exists public.get_lesson_catalog();
create function public.get_lesson_catalog()
returns table (
  id bigint,
  external_id text,
  level_code text,
  level_position integer,
  module_id bigint,
  module_external_id text,
  module_title text,
  module_position integer,
  lesson_number integer,
  module_lesson_number integer,
  global_order integer,
  title text,
  summary text,
  state text,
  is_checkpoint boolean,
  progress_percent integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    l.id, l.external_id, m.level_code, lv.position, m.id, m.external_id, m.title, m.position,
    l.level_lesson_number, l.module_lesson_number, l.global_order, l.title, l.summary,
    case
      when p.status = 'completed' then 'completed'
      when private.is_admin() and p.status = 'in_progress' then 'current'
      when private.is_admin() then 'available'
      when a.unlocked and p.status = 'in_progress' then 'current'
      when a.unlocked then 'available'
      else 'locked'
    end,
    l.is_checkpoint,
    coalesce(case
      when p.status = 'completed' then 100
      when blocks.total_blocks > 0 then least(100, round((p.current_position::numeric / blocks.total_blocks) * 100)::integer)
      else 0 end, 0)
  from public.lessons l
  join public.modules m on m.id = l.module_id
  join public.levels lv on lv.code = m.level_code
  left join public.student_lesson_access a
    on a.lesson_id = l.id and a.student_id = (select auth.uid()) and a.unlocked
  left join public.lesson_progress p
    on p.lesson_id = l.id and p.student_id = (select auth.uid())
  left join lateral (
    select count(*)::integer total_blocks from public.lesson_blocks b where b.lesson_id = l.id
  ) blocks on true
  where l.published and not l.is_legacy
  order by l.global_order
$$;

create or replace function public.get_lesson_detail(p_lesson_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  if not private.can_access_lesson(p_lesson_id) then
    raise exception 'lesson_not_accessible' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'id', l.id, 'external_id', l.external_id, 'level_code', m.level_code,
    'lesson_number', l.level_lesson_number, 'module_lesson_number', l.module_lesson_number,
    'global_order', l.global_order, 'title', l.title, 'summary', l.summary,
    'xp_reward', l.xp_reward, 'is_checkpoint', l.is_checkpoint,
    'can_do', l.can_do, 'metadata', l.metadata,
    'saved_position', coalesce((select p.current_position from public.lesson_progress p
      where p.student_id = (select auth.uid()) and p.lesson_id = l.id), 0),
    'blocks', coalesce((select jsonb_agg(jsonb_build_object(
      'id', b.id, 'external_id', b.external_id, 'block_type', b.block_type,
      'position', b.position, 'title', b.title, 'content', b.content,
      'audio_path', b.audio_path, 'slow_audio_path', b.slow_audio_path,
      'audio_status', b.audio_status, 'audio_required', b.audio_required,
      'audio_role', b.audio_role, 'transcript', b.transcript,
      'exercise', case when e.id is null then null else jsonb_build_object(
        'id', e.id, 'external_id', e.external_id, 'exercise_type', e.exercise_type,
        'prompt', e.prompt, 'instruction', e.instruction, 'content', e.content,
        'feedback_correct', e.feedback_correct, 'feedback_incorrect', e.feedback_incorrect,
        'grading_mode', e.grading_mode,
        'options', coalesce((select jsonb_agg(jsonb_build_object(
          'id', o.id, 'label', o.label, 'value', o.value, 'position', o.position
        ) order by o.position) from public.exercise_options o where o.exercise_id = e.id), '[]'::jsonb)
      ) end
    ) order by b.position)
    from public.lesson_blocks b left join public.exercises e on e.lesson_block_id = b.id
    where b.lesson_id = l.id), '[]'::jsonb)
  ) into result
  from public.lessons l join public.modules m on m.id = l.module_id
  where l.id = p_lesson_id and l.published and not l.is_legacy;

  if result is null then raise exception 'lesson_not_found' using errcode = 'P0002'; end if;
  return result;
end;
$$;

create or replace function public.submit_exercise_attempt(p_exercise_id bigint, p_answer jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  key_external_id text;
  expected_answer jsonb;
  accepted_answers jsonb;
  answer_rationale text;
  target_lesson_id bigint;
  mode text;
  is_correct boolean := false;
  correct_message text;
  incorrect_message text;
  answer_text text;
begin
  select b.lesson_id, e.grading_mode, e.feedback_correct, e.feedback_incorrect,
    k.external_id, k.expected_answer, k.accepted_answers, k.rationale
  into target_lesson_id, mode, correct_message, incorrect_message,
    key_external_id, expected_answer, accepted_answers, answer_rationale
  from public.exercises e
  join public.lesson_blocks b on b.id = e.lesson_block_id
  left join private.answer_keys k on k.external_id = e.external_id
  where e.id = p_exercise_id;

  if target_lesson_id is null or not private.can_access_lesson(target_lesson_id) then
    raise exception 'exercise_not_accessible' using errcode = '42501';
  end if;
  if p_answer is null or p_answer = 'null'::jsonb then
    raise exception 'answer_required' using errcode = '22023';
  end if;

  if mode = 'subjective' then
    insert into public.exercise_attempts (student_id, exercise_id, answer, correct, submission_status)
    values ((select auth.uid()), p_exercise_id, p_answer, null, 'submitted');
    return jsonb_build_object(
      'correct', null, 'submitted', true,
      'message', 'Resposta enviada. Ela foi registrada para revisão.',
      'explanation', 'Atividades abertas não recebem uma nota automática.'
    );
  end if;

  if key_external_id is null then
    raise exception 'answer_key_missing' using errcode = 'P0002';
  end if;
  answer_text := lower(trim(p_answer #>> '{}'));
  is_correct := (
    expected_answer is not null
    and lower(trim(expected_answer #>> '{}')) = answer_text
  ) or exists (
    select 1 from jsonb_array_elements_text(coalesce(accepted_answers, '[]'::jsonb)) candidate
    where lower(trim(candidate)) = answer_text
  );

  insert into public.exercise_attempts (student_id, exercise_id, answer, correct, submission_status)
  values ((select auth.uid()), p_exercise_id, p_answer, is_correct, 'graded');
  return jsonb_build_object(
    'correct', is_correct, 'submitted', true,
    'message', case when is_correct then correct_message else incorrect_message end,
    'explanation', case when is_correct then 'Muito bem. Continue avançando.' else coalesce(answer_rationale, 'Revise o exemplo e tente novamente.') end
  );
end;
$$;

create or replace function public.complete_lesson(p_lesson_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  total_exercises integer;
  submitted_exercises integer;
  graded_exercises integer;
  correct_answers integer;
  score_percent integer;
  reward integer;
  checkpoint boolean;
  next_lesson_id bigint;
  current_order integer;
  next_level text;
  awarded integer := 0;
begin
  if not private.can_access_lesson(p_lesson_id) then
    raise exception 'lesson_not_accessible' using errcode = '42501';
  end if;
  select l.xp_reward, l.is_checkpoint, l.global_order into reward, checkpoint, current_order
  from public.lessons l where l.id = p_lesson_id and l.published and not l.is_legacy;
  if current_order is null then raise exception 'lesson_not_found' using errcode = 'P0002'; end if;

  select count(*)::integer,
    count(*) filter (where e.grading_mode = 'automatic')::integer
  into total_exercises, graded_exercises
  from public.exercises e join public.lesson_blocks b on b.id = e.lesson_block_id
  where b.lesson_id = p_lesson_id;

  select count(*)::integer into submitted_exercises from (
    select distinct a.exercise_id
    from public.exercise_attempts a
    join public.exercises e on e.id = a.exercise_id
    join public.lesson_blocks b on b.id = e.lesson_block_id
    where a.student_id = (select auth.uid()) and b.lesson_id = p_lesson_id
  ) submitted;
  if submitted_exercises < total_exercises then
    raise exception 'lesson_exercises_incomplete' using errcode = 'P0001';
  end if;

  select count(*)::integer into correct_answers from (
    select distinct a.exercise_id
    from public.exercise_attempts a
    join public.exercises e on e.id = a.exercise_id
    join public.lesson_blocks b on b.id = e.lesson_block_id
    where a.student_id = (select auth.uid()) and b.lesson_id = p_lesson_id
      and e.grading_mode = 'automatic' and a.correct
  ) correct;
  score_percent := case when graded_exercises = 0 then 100
    else round((correct_answers::numeric / graded_exercises) * 100)::integer end;
  reward := reward
    + case when graded_exercises > 0 and correct_answers = graded_exercises then 20 else 0 end
    + case when checkpoint then 50 else 0 end;

  insert into public.lesson_progress
    (student_id, lesson_id, status, current_position, score_percent, started_at, completed_at, updated_at)
  values ((select auth.uid()), p_lesson_id, 'completed', 0, score_percent, now(), now(), now())
  on conflict (student_id, lesson_id) do update set
    status = 'completed', score_percent = greatest(coalesce(public.lesson_progress.score_percent, 0), excluded.score_percent),
    completed_at = coalesce(public.lesson_progress.completed_at, now()), updated_at = now();

  insert into public.xp_events (student_id, points, event_type, source_id)
  values ((select auth.uid()), reward, 'lesson_completed', p_lesson_id)
  on conflict (student_id, event_type, source_id) where source_id is not null do nothing;
  if found then awarded := reward; end if;

  insert into public.review_schedule (student_id, lesson_id, review_offset_days, due_at)
  select (select auth.uid()), p_lesson_id, days, now() + make_interval(days => days)
  from unnest(array[1,3,7,21]) days
  on conflict (student_id, lesson_id, review_offset_days) do nothing;

  select l.id, m.level_code into next_lesson_id, next_level
  from public.lessons l join public.modules m on m.id = l.module_id
  where l.published and not l.is_legacy and l.global_order > current_order
  order by l.global_order limit 1;
  if next_lesson_id is not null then
    insert into public.student_lesson_access (student_id, lesson_id, unlocked)
    values ((select auth.uid()), next_lesson_id, true)
    on conflict (student_id, lesson_id) do update set unlocked = true, unlocked_at = now();
    update public.profiles set current_level_code = next_level, updated_at = now()
    where id = (select auth.uid());
  else
    update public.profiles set course_completed_at = coalesce(course_completed_at, now()), updated_at = now()
    where id = (select auth.uid());
  end if;

  return jsonb_build_object(
    'correct_answers', correct_answers, 'total_exercises', graded_exercises,
    'submitted_exercises', submitted_exercises, 'score_percent', score_percent,
    'xp_awarded', awarded, 'next_lesson_id', next_lesson_id,
    'course_completed', next_lesson_id is null
  );
end;
$$;

create or replace function public.get_dashboard_metrics()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  with activity_dates as (
    select distinct activity_at::date activity_date from (
      select a.attempted_at activity_at from public.exercise_attempts a where a.student_id = (select auth.uid())
      union all
      select p.completed_at from public.lesson_progress p where p.student_id = (select auth.uid()) and p.completed_at is not null
    ) activities
  ), numbered as (
    select activity_date, activity_date - row_number() over (order by activity_date)::integer grp from activity_dates
  ), streaks as (
    select min(activity_date) start_date, max(activity_date) end_date, count(*)::integer days
    from numbered group by grp
  )
  select jsonb_build_object(
    'xp', coalesce((select sum(x.points) from public.xp_events x where x.student_id = (select auth.uid())), 0),
    'completed_lessons', (select count(*) from public.lesson_progress p join public.lessons l on l.id = p.lesson_id
      where p.student_id = (select auth.uid()) and p.status = 'completed' and not l.is_legacy),
    'streak', coalesce((select days from streaks
      where end_date in (current_date, current_date - 1) order by end_date desc limit 1), 0)
  )
$$;

create or replace function public.submit_grammar_clinic_exercise(p_exercise_id bigint, p_answer jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not exists (
    select 1 from public.grammar_clinic_exercises e
    join public.grammar_clinics c on c.id = e.clinic_id
    where e.id = p_exercise_id and c.published
  ) then raise exception 'clinic_exercise_not_accessible' using errcode = '42501'; end if;
  insert into public.grammar_clinic_submissions (student_id, exercise_id, answer)
  values ((select auth.uid()), p_exercise_id, p_answer);
  return jsonb_build_object('submitted', true, 'message', 'Resposta registrada para revisão.');
end;
$$;

create or replace function public.get_review_resources()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'due_reviews', coalesce((select jsonb_agg(jsonb_build_object(
      'id', r.id, 'lesson_id', r.lesson_id, 'lesson_title', l.title,
      'level_code', m.level_code, 'due_at', r.due_at, 'offset_days', r.review_offset_days
    ) order by r.due_at) from public.review_schedule r
      join public.lessons l on l.id = r.lesson_id join public.modules m on m.id = l.module_id
      where r.student_id = (select auth.uid()) and r.completed_at is null), '[]'::jsonb),
    'clinics', coalesce((select jsonb_agg(jsonb_build_object(
      'id', c.id, 'external_id', c.external_id, 'level_code', c.level_code,
      'title', c.title, 'focus', c.focus, 'why', c.why_text, 'examples', c.examples,
      'recycle_in', c.recycle_in, 'visual_external_id', c.visual_external_id,
      'exercises', coalesce((select jsonb_agg(jsonb_build_object(
        'id', e.id, 'external_id', e.external_id, 'type', e.exercise_type,
        'position', e.position, 'prompt', e.prompt, 'instruction', e.instruction,
        'content', e.content, 'grading_mode', e.grading_mode
      ) order by e.position) from public.grammar_clinic_exercises e where e.clinic_id = c.id), '[]'::jsonb)
    ) order by lv.position, c.position) from public.grammar_clinics c
      join public.levels lv on lv.code = c.level_code where c.published), '[]'::jsonb)
  )
$$;

create or replace function public.get_visual_asset(p_external_id text)
returns table (storage_path text, alt_text text, lesson_id bigint, grammar_clinic_external_id text)
language sql
stable
security invoker
set search_path = ''
as $$
  select a.storage_path, a.alt_text, a.lesson_id, a.grammar_clinic_external_id
  from public.lesson_assets a where a.external_id = p_external_id
$$;

create or replace function public.import_private_answer_keys(p_entries jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare entry record; imported integer := 0;
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  for entry in select key, value from jsonb_each(p_entries) loop
    insert into private.answer_keys (
      external_id, expected_answer, accepted_answers, model_answer, rationale, rubric, source_metadata, updated_at
    ) values (
      entry.key,
      entry.value -> 'answer',
      entry.value -> 'accepted',
      entry.value ->> 'model_answer',
      entry.value ->> 'rationale',
      entry.value -> 'rubric',
      entry.value - array['answer','accepted','model_answer','rationale','rubric'],
      now()
    ) on conflict (external_id) do update set
      expected_answer = excluded.expected_answer,
      accepted_answers = excluded.accepted_answers,
      model_answer = excluded.model_answer,
      rationale = excluded.rationale,
      rubric = excluded.rubric,
      source_metadata = excluded.source_metadata,
      updated_at = now();
    imported := imported + 1;
  end loop;
  return imported;
end;
$$;

drop function if exists public.get_admin_audio_overview();
create function public.get_admin_audio_overview()
returns table (
  lesson_id bigint, level_code text, module_id bigint, module_title text,
  lesson_number integer, title text, ready_count bigint, missing_count bigint,
  generating_count bigint, failed_count bigint, total_count bigint
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  if not private.is_admin() then raise exception 'admin_required' using errcode = '42501'; end if;
  return query select l.id, m.level_code, m.id, m.title, l.level_lesson_number, l.title,
    count(b.id) filter (where b.audio_status = 'ready'),
    count(b.id) filter (where b.audio_status = 'missing'),
    count(b.id) filter (where b.audio_status = 'generating'),
    count(b.id) filter (where b.audio_status = 'failed'), count(b.id)
  from public.lessons l join public.modules m on m.id = l.module_id
  left join public.lesson_blocks b on b.lesson_id = l.id and b.audio_required
  where l.published and not l.is_legacy
  group by l.id, m.level_code, m.id, m.title, l.level_lesson_number, l.title, l.global_order
  order by l.global_order;
end;
$$;

-- Existing users receive the first curriculum lesson after the importer publishes it.
-- The importer performs this operation after a complete, validated upsert so no user
-- can enter a partially imported course.

revoke execute on function public.get_lesson_catalog() from public, anon;
revoke execute on function public.get_lesson_detail(bigint) from public, anon;
revoke execute on function public.get_dashboard_metrics() from public, anon;
revoke execute on function public.get_review_resources() from public, anon;
revoke execute on function public.submit_grammar_clinic_exercise(bigint, jsonb) from public, anon;
revoke execute on function public.get_visual_asset(text) from public, anon;
grant execute on function public.get_lesson_catalog(), public.get_lesson_detail(bigint),
  public.get_dashboard_metrics(), public.get_review_resources(),
  public.submit_grammar_clinic_exercise(bigint, jsonb), public.get_visual_asset(text)
  to authenticated;

revoke execute on function public.import_private_answer_keys(jsonb) from public, anon, authenticated;
grant execute on function public.import_private_answer_keys(jsonb) to service_role;
grant execute on function public.submit_exercise_attempt(bigint, jsonb), public.complete_lesson(bigint),
  public.get_admin_audio_overview() to authenticated;
grant execute on all functions in schema public to service_role;
