-- English Journey: clean rebuild of the reusable Supabase project.
-- The previous public schema belonged to an unrelated application.

drop schema if exists public cascade;
create schema public authorization postgres;
comment on schema public is 'Barreto English Journey API';

grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, service_role;

-- Remove accounts from the previous application. The project owner explicitly
-- authorized full reuse of this Supabase project.
delete from auth.users;

create schema if not exists private authorization postgres;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated;

create table public.levels (
  code text primary key check (code in ('A1', 'A2')),
  title text not null,
  position integer not null unique check (position > 0)
);

create table public.modules (
  id bigint generated by default as identity primary key,
  level_code text not null references public.levels(code) on update cascade on delete restrict,
  title text not null,
  position integer not null unique check (position > 0)
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.modules(id) on delete cascade,
  lesson_number integer not null unique check (lesson_number > 0),
  week_number integer,
  title text not null,
  summary text not null default '',
  xp_reward integer not null default 50 check (xp_reward >= 0),
  is_checkpoint boolean not null default false,
  published boolean not null default false,
  position integer not null unique check (position > 0),
  created_at timestamptz not null default now()
);

create table public.lesson_blocks (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  block_type text not null check (block_type in (
    'text', 'vocabulary', 'grammar', 'example', 'multiple_choice',
    'fill_blank', 'reorder_words', 'true_false', 'listening',
    'speaking', 'reading', 'writing', 'checkpoint'
  )),
  position integer not null check (position > 0),
  title text,
  content jsonb not null default '{}'::jsonb,
  unique (lesson_id, position)
);

create table public.exercises (
  id bigint generated by default as identity primary key,
  lesson_block_id bigint not null unique references public.lesson_blocks(id) on delete cascade,
  exercise_type text not null,
  prompt text not null,
  instruction text,
  content jsonb not null default '{}'::jsonb,
  feedback_correct text not null,
  feedback_incorrect text not null
);

create table private.exercise_answers (
  exercise_id bigint primary key references public.exercises(id) on delete cascade,
  expected_answer jsonb not null
);

create table public.exercise_options (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  label text not null,
  value text not null,
  position integer not null check (position > 0),
  unique (exercise_id, position)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username = lower(username) and username ~ '^[a-z0-9._-]{3,40}$'),
  display_name text not null check (length(trim(display_name)) between 1 and 80),
  role text not null default 'student' check (role in ('student', 'admin')),
  current_level_code text not null default 'A1' references public.levels(code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index profiles_username_lower_idx on public.profiles (lower(username));

create table public.student_lesson_access (
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  unlocked boolean not null default true,
  unlocked_at timestamptz not null default now(),
  unlocked_by uuid references public.profiles(id) on delete set null,
  primary key (student_id, lesson_id)
);

create table public.lesson_progress (
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'completed')),
  current_position integer not null default 0 check (current_position >= 0),
  score_percent integer check (score_percent between 0 and 100),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (student_id, lesson_id)
);

create table public.exercise_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  answer jsonb not null,
  correct boolean not null,
  attempted_at timestamptz not null default now()
);

create table public.xp_events (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  points integer not null check (points >= 0),
  event_type text not null,
  source_id bigint,
  created_at timestamptz not null default now()
);
create unique index xp_events_once_idx on public.xp_events (student_id, event_type, source_id)
  where source_id is not null;

create index modules_level_idx on public.modules(level_code, position);
create index lessons_module_idx on public.lessons(module_id, position);
create index lesson_blocks_lesson_idx on public.lesson_blocks(lesson_id, position);
create index exercise_options_exercise_idx on public.exercise_options(exercise_id, position);
create index lesson_access_student_idx on public.student_lesson_access(student_id, unlocked);
create index lesson_progress_student_idx on public.lesson_progress(student_id, status);
create index exercise_attempts_student_idx on public.exercise_attempts(student_id, exercise_id, attempted_at desc);
create index xp_events_student_idx on public.xp_events(student_id, created_at desc);

insert into public.levels (code, title, position) values
  ('A1', 'Primeiros passos', 1),
  ('A2', 'Conversas do cotidiano', 2);

insert into public.modules (id, level_code, title, position) values
  (1, 'A1', 'A1.1 · First Steps', 1),
  (2, 'A1', 'A1.2 · Everyday English', 2),
  (3, 'A2', 'A2.1 · Expanding Stories', 3),
  (4, 'A2', 'A2.2 · Real Conversations', 4);

insert into public.lessons
  (id, module_id, lesson_number, week_number, title, summary, xp_reward, is_checkpoint, published, position)
values
  (1, 1, 1, 1, 'Hello!', 'Cumprimentos essenciais para começar e encerrar conversas.', 50, false, true, 1),
  (2, 1, 2, 2, 'Me and My Family', 'Família e apresentações.', 50, false, true, 2),
  (3, 1, 3, 3, 'My Everyday Life', 'Rotina, horas e frequência.', 50, false, true, 3),
  (4, 1, 4, 4, 'Things Around Me', 'Casa, objetos e posições.', 50, false, true, 4),
  (5, 1, 5, null, 'Checkpoint A1.1', 'Revisão do primeiro ciclo.', 100, true, true, 5),
  (6, 2, 6, 5, 'Food & Drinks', 'Pedidos, alimentos e quantidades.', 50, false, true, 6),
  (7, 2, 7, 6, 'What Are You Doing?', 'Ações acontecendo agora.', 50, false, true, 7),
  (8, 2, 8, 7, 'Can You Help Me?', 'Habilidades, pedidos e direções.', 50, false, true, 8),
  (9, 2, 9, 8, 'A1 Final', 'Projeto e checkpoint A1.', 100, true, true, 9),
  (10, 3, 10, 9, 'The Past', 'Primeiras histórias no passado.', 50, false, true, 10),
  (11, 3, 11, 10, 'Stories and Experiences', 'Sequência e storytelling.', 50, false, true, 11),
  (12, 3, 12, 11, 'Plans and the Future', 'Planos, viagens e futuro.', 50, false, true, 12),
  (13, 3, 13, 12, 'Comparing Things', 'Comparações e superlativos.', 50, false, true, 13),
  (14, 3, 14, null, 'Checkpoint A2.1', 'Revisão do primeiro ciclo A2.', 100, true, true, 14),
  (15, 4, 15, 13, 'Life Experiences', 'Experiências de vida.', 50, false, true, 15),
  (16, 4, 16, 14, 'Rules, Advice and Obligations', 'Conselhos, regras e obrigações.', 50, false, true, 16),
  (17, 4, 17, 15, 'Real Conversations', 'Restaurante, hotel, aeroporto e trabalho.', 50, false, true, 17),
  (18, 4, 18, 16, 'A2 Final', 'Projeto final e checkpoint A2.', 100, true, true, 18);

insert into public.lesson_blocks (id, lesson_id, block_type, position, title, content) values
  (1, 1, 'text', 1, 'Seu primeiro passo', '{"body":"Hoje você vai aprender a cumprimentar alguém em diferentes momentos do dia. Escute, repita e use sem pressa."}'),
  (2, 1, 'vocabulary', 2, 'Hello / Hi', '{"term":"Hello!","translation":"Olá!","example":"Hello, my name is Maria.","note":"Hi é uma alternativa um pouco mais informal."}'),
  (3, 1, 'vocabulary', 3, 'Morning', '{"term":"Good morning","translation":"Bom dia","example":"Good morning, Ana!"}'),
  (4, 1, 'vocabulary', 4, 'Later in the day', '{"term":"Good afternoon","translation":"Boa tarde","example":"Good afternoon, Mr. Lee."}'),
  (5, 1, 'vocabulary', 5, 'Evening', '{"term":"Good evening","translation":"Boa noite ao chegar","example":"Good evening. How are you?"}'),
  (6, 1, 'vocabulary', 6, 'Ending a conversation', '{"term":"Goodbye","translation":"Até logo / tchau","example":"Goodbye! See you tomorrow.","note":"Use Good night ao se despedir no fim da noite ou antes de dormir."}'),
  (7, 1, 'vocabulary', 7, 'Being polite', '{"term":"Thank you","translation":"Obrigada / obrigado","example":"Thank you for your help."}'),
  (8, 1, 'multiple_choice', 8, null, '{}'),
  (9, 1, 'listening', 9, null, '{}'),
  (10, 1, 'fill_blank', 10, null, '{}'),
  (11, 1, 'speaking', 11, null, '{"phrase":"Hello, my name is Maria.","translation":"Olá, meu nome é Maria.","disclaimer":"A prática ajuda a ganhar confiança; esta versão não mede sua pronúncia cientificamente."}'),
  (12, 1, 'checkpoint', 12, 'Pronta para usar', '{"body":"Você já consegue iniciar uma conversa, escolher um cumprimento para cada horário e se despedir com naturalidade."}');

insert into public.exercises
  (id, lesson_block_id, exercise_type, prompt, instruction, content, feedback_correct, feedback_incorrect)
values
  (101, 8, 'multiple_choice', 'Você encontra uma pessoa às 9h. O que diz?', 'Escolha a resposta correta.', '{}', 'Isso mesmo: pela manhã, usamos “Good morning”.', 'Às 9h ainda é manhã. Use “Good morning”.'),
  (102, 9, 'listening', 'Qual frase você ouviu?', 'Ouça em velocidade normal ou reduzida.', '{"speech":"Good evening. Nice to meet you."}', 'Perfeito. “Good evening” é usado ao encontrar alguém à noite.', 'Escute novamente: a frase começa com “Good evening”.'),
  (103, 10, 'fill_blank', 'Good ___! See you tomorrow.', 'Complete a despedida.', '{"placeholder":"Digite uma palavra"}', 'Correto. “Goodbye” encerra a conversa.', 'Aqui queremos encerrar a conversa. A palavra é “bye”.');

insert into private.exercise_answers (exercise_id, expected_answer) values
  (101, '"good_morning"'),
  (102, '"evening"'),
  (103, '["bye","goodbye"]');

insert into public.exercise_options (id, exercise_id, label, value, position) values
  (1, 101, 'Good morning!', 'good_morning', 1),
  (2, 101, 'Good evening!', 'good_evening', 2),
  (3, 101, 'Goodbye!', 'goodbye', 3),
  (4, 102, 'Good evening. Nice to meet you.', 'evening', 1),
  (5, 102, 'Good morning. See you tomorrow.', 'morning', 2);

select setval(pg_get_serial_sequence('public.modules', 'id'), (select max(id) from public.modules));
select setval(pg_get_serial_sequence('public.lessons', 'id'), (select max(id) from public.lessons));
select setval(pg_get_serial_sequence('public.lesson_blocks', 'id'), (select max(id) from public.lesson_blocks));
select setval(pg_get_serial_sequence('public.exercises', 'id'), (select max(id) from public.exercises));
select setval(pg_get_serial_sequence('public.exercise_options', 'id'), (select max(id) from public.exercise_options));

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  )
$$;

create or replace function private.can_access_lesson(p_lesson_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null and (
    private.is_admin()
    or exists (
      select 1
      from public.student_lesson_access
      where student_id = (select auth.uid())
        and lesson_id = p_lesson_id
        and unlocked
    )
  )
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  base_username text;
  final_username text;
begin
  base_username := lower(regexp_replace(
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(coalesce(new.email, 'student'), '@', 1)),
    '[^a-z0-9._-]', '', 'g'
  ));
  if length(base_username) < 3 then
    base_username := 'student';
  end if;

  final_username := left(base_username, 31);
  if exists (select 1 from public.profiles where lower(username) = lower(final_username)) then
    final_username := left(base_username, 22) || '-' || left(new.id::text, 8);
  end if;

  insert into public.profiles (id, username, display_name, role, current_level_code)
  values (
    new.id,
    final_username,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), initcap(replace(final_username, '.', ' '))),
    'student',
    'A1'
  );

  insert into public.student_lesson_access (student_id, lesson_id, unlocked)
  select new.id, id, true from public.lessons
  where published
  order by position
  limit 1;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

alter table public.levels enable row level security;
alter table public.modules enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_blocks enable row level security;
alter table public.exercises enable row level security;
alter table public.exercise_options enable row level security;
alter table public.profiles enable row level security;
alter table public.student_lesson_access enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.exercise_attempts enable row level security;
alter table public.xp_events enable row level security;

create policy "authenticated read levels"
  on public.levels for select to authenticated using (true);
create policy "authenticated read modules"
  on public.modules for select to authenticated using (true);
create policy "authenticated read published lessons"
  on public.lessons for select to authenticated using (published);
create policy "students read accessible lesson blocks"
  on public.lesson_blocks for select to authenticated
  using (private.can_access_lesson(lesson_id));
create policy "students read accessible exercises"
  on public.exercises for select to authenticated
  using (exists (
    select 1 from public.lesson_blocks b
    where b.id = lesson_block_id and private.can_access_lesson(b.lesson_id)
  ));
create policy "students read accessible exercise options"
  on public.exercise_options for select to authenticated
  using (exists (
    select 1
    from public.exercises e
    join public.lesson_blocks b on b.id = e.lesson_block_id
    where e.id = exercise_id and private.can_access_lesson(b.lesson_id)
  ));
create policy "profiles read self or admin"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id or private.is_admin());
create policy "lesson access read self or admin"
  on public.student_lesson_access for select to authenticated
  using ((select auth.uid()) = student_id or private.is_admin());
create policy "lesson progress read self or admin"
  on public.lesson_progress for select to authenticated
  using ((select auth.uid()) = student_id or private.is_admin());
create policy "attempts read self or admin"
  on public.exercise_attempts for select to authenticated
  using ((select auth.uid()) = student_id or private.is_admin());
create policy "xp read self or admin"
  on public.xp_events for select to authenticated
  using ((select auth.uid()) = student_id or private.is_admin());

create or replace function public.get_lesson_catalog()
returns table (
  id bigint,
  level_code text,
  module_title text,
  week_number integer,
  title text,
  summary text,
  state text,
  is_checkpoint boolean,
  progress_percent integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    l.id,
    m.level_code,
    m.title,
    l.week_number,
    l.title,
    l.summary,
    case
      when p.status = 'completed' then 'completed'
      when a.unlocked and p.status = 'in_progress' then 'current'
      when a.unlocked then 'available'
      when l.is_checkpoint then 'checkpoint'
      else 'locked'
    end,
    l.is_checkpoint,
    coalesce(
      case
        when p.status = 'completed' then 100
        when blocks.total_blocks > 0 then round((p.current_position::numeric / blocks.total_blocks) * 100)::integer
        else 0
      end,
      0
    )
  from public.lessons l
  join public.modules m on m.id = l.module_id
  left join public.student_lesson_access a
    on a.lesson_id = l.id and a.student_id = (select auth.uid()) and a.unlocked
  left join public.lesson_progress p
    on p.lesson_id = l.id and p.student_id = (select auth.uid())
  left join lateral (
    select count(*)::integer as total_blocks
    from public.lesson_blocks b
    where b.lesson_id = l.id
  ) blocks on true
  where l.published
  order by l.position
$$;

create or replace function public.save_lesson_position(p_lesson_id bigint, p_position integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.can_access_lesson(p_lesson_id) then
    raise exception 'lesson_not_accessible' using errcode = '42501';
  end if;

  insert into public.lesson_progress
    (student_id, lesson_id, status, current_position, started_at, updated_at)
  values
    ((select auth.uid()), p_lesson_id, 'in_progress', greatest(p_position, 0), now(), now())
  on conflict (student_id, lesson_id) do update
    set status = case when public.lesson_progress.status = 'completed' then 'completed' else 'in_progress' end,
        current_position = greatest(public.lesson_progress.current_position, excluded.current_position),
        started_at = coalesce(public.lesson_progress.started_at, now()),
        updated_at = now();
end;
$$;

create or replace function public.submit_exercise_attempt(p_exercise_id bigint, p_answer jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  expected jsonb;
  target_lesson_id bigint;
  is_correct boolean := false;
  correct_message text;
  incorrect_message text;
begin
  select a.expected_answer, b.lesson_id, e.feedback_correct, e.feedback_incorrect
  into expected, target_lesson_id, correct_message, incorrect_message
  from private.exercise_answers a
  join public.exercises e on e.id = a.exercise_id
  join public.lesson_blocks b on b.id = e.lesson_block_id
  where a.exercise_id = p_exercise_id;

  if expected is null or not private.can_access_lesson(target_lesson_id) then
    raise exception 'exercise_not_accessible' using errcode = '42501';
  end if;

  if jsonb_typeof(expected) = 'array' then
    select exists (
      select 1 from jsonb_array_elements_text(expected) candidate
      where lower(trim(candidate)) = lower(trim(p_answer #>> '{}'))
    ) into is_correct;
  else
    is_correct := lower(trim(expected #>> '{}')) = lower(trim(p_answer #>> '{}'));
  end if;

  insert into public.exercise_attempts (student_id, exercise_id, answer, correct)
  values ((select auth.uid()), p_exercise_id, p_answer, is_correct);

  return jsonb_build_object(
    'correct', is_correct,
    'message', case when is_correct then correct_message else incorrect_message end,
    'explanation', case when is_correct then 'Muito bem. Continue avançando.' else 'Revise o exemplo e tente novamente.' end
  );
end;
$$;

create or replace function public.complete_lesson(p_lesson_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  total_exercises integer;
  correct_answers integer;
  score_percent integer;
  reward integer;
  checkpoint boolean;
  next_lesson_id bigint;
begin
  if not private.can_access_lesson(p_lesson_id) then
    raise exception 'lesson_not_accessible' using errcode = '42501';
  end if;

  select l.xp_reward, l.is_checkpoint into reward, checkpoint
  from public.lessons l where l.id = p_lesson_id;

  select count(*)::integer into total_exercises
  from public.exercises e
  join public.lesson_blocks b on b.id = e.lesson_block_id
  where b.lesson_id = p_lesson_id;

  select count(distinct a.exercise_id)::integer into correct_answers
  from public.exercise_attempts a
  join public.exercises e on e.id = a.exercise_id
  join public.lesson_blocks b on b.id = e.lesson_block_id
  where a.student_id = (select auth.uid())
    and b.lesson_id = p_lesson_id
    and a.correct;

  score_percent := case when total_exercises = 0 then 100 else round((correct_answers::numeric / total_exercises) * 100)::integer end;
  reward := reward
    + case when total_exercises > 0 and correct_answers = total_exercises then 20 else 0 end
    + case when checkpoint then 50 else 0 end;

  insert into public.lesson_progress
    (student_id, lesson_id, status, current_position, score_percent, started_at, completed_at, updated_at)
  values
    ((select auth.uid()), p_lesson_id, 'completed', 0, score_percent, now(), now(), now())
  on conflict (student_id, lesson_id) do update
    set status = 'completed',
        score_percent = greatest(coalesce(public.lesson_progress.score_percent, 0), excluded.score_percent),
        completed_at = coalesce(public.lesson_progress.completed_at, now()),
        updated_at = now();

  insert into public.xp_events (student_id, points, event_type, source_id)
  values ((select auth.uid()), reward, 'lesson_completed', p_lesson_id)
  on conflict (student_id, event_type, source_id) where source_id is not null do nothing;

  select next_lesson.id into next_lesson_id
  from public.lessons current_lesson
  join public.lessons next_lesson on next_lesson.position > current_lesson.position and next_lesson.published
  where current_lesson.id = p_lesson_id
  order by next_lesson.position
  limit 1;

  if next_lesson_id is not null then
    insert into public.student_lesson_access (student_id, lesson_id, unlocked)
    values ((select auth.uid()), next_lesson_id, true)
    on conflict (student_id, lesson_id) do update set unlocked = true, unlocked_at = now();
  end if;

  return jsonb_build_object(
    'correct_answers', correct_answers,
    'total_exercises', total_exercises,
    'score_percent', score_percent,
    'xp_awarded', reward
  );
end;
$$;

create or replace function public.get_admin_student_overview()
returns table (
  id uuid,
  display_name text,
  username text,
  level_code text,
  progress_percent integer,
  accuracy_percent integer,
  xp bigint,
  last_activity timestamptz,
  completed_lessons bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  return query
  select
    p.id,
    p.display_name,
    p.username,
    p.current_level_code,
    coalesce(round(100.0 * count(lp.lesson_id) filter (where lp.status = 'completed') / nullif((select count(*) from public.lessons where published), 0))::integer, 0),
    coalesce(round(100.0 * count(ea.id) filter (where ea.correct) / nullif(count(ea.id), 0))::integer, 0),
    coalesce((select sum(x.points) from public.xp_events x where x.student_id = p.id), 0),
    max(ea.attempted_at),
    count(distinct lp.lesson_id) filter (where lp.status = 'completed')
  from public.profiles p
  left join public.lesson_progress lp on lp.student_id = p.id
  left join public.exercise_attempts ea on ea.student_id = p.id
  where p.role = 'student'
  group by p.id, p.display_name, p.username, p.current_level_code;
end;
$$;

create or replace function public.admin_unlock_lesson(p_student_id uuid, p_lesson_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  insert into public.student_lesson_access (student_id, lesson_id, unlocked, unlocked_by)
  values (p_student_id, p_lesson_id, true, (select auth.uid()))
  on conflict (student_id, lesson_id) do update
    set unlocked = true, unlocked_at = now(), unlocked_by = (select auth.uid());
end;
$$;

create or replace function public.admin_lock_lesson(p_student_id uuid, p_lesson_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  insert into public.student_lesson_access (student_id, lesson_id, unlocked, unlocked_by)
  values (p_student_id, p_lesson_id, false, (select auth.uid()))
  on conflict (student_id, lesson_id) do update
    set unlocked = false, unlocked_at = now(), unlocked_by = (select auth.uid());
end;
$$;

revoke all on all tables in schema public from anon, authenticated;
grant select on public.levels, public.modules, public.lessons, public.lesson_blocks,
  public.exercises, public.exercise_options, public.profiles, public.student_lesson_access,
  public.lesson_progress, public.exercise_attempts, public.xp_events to authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function public.get_lesson_catalog() to authenticated;
grant execute on function public.save_lesson_position(bigint, integer) to authenticated;
grant execute on function public.submit_exercise_attempt(bigint, jsonb) to authenticated;
grant execute on function public.complete_lesson(bigint) to authenticated;
grant execute on function public.get_admin_student_overview() to authenticated;
grant execute on function public.admin_unlock_lesson(uuid, bigint) to authenticated;
grant execute on function public.admin_lock_lesson(uuid, bigint) to authenticated;
grant execute on all functions in schema public to service_role;

revoke all on all functions in schema private from public, anon;
grant execute on function private.is_admin() to authenticated, service_role;
grant execute on function private.can_access_lesson(bigint) to authenticated, service_role;
grant execute on function private.handle_new_user() to supabase_auth_admin, service_role;

grant select on private.exercise_answers to service_role;
