-- Phase 3/4 infrastructure for the A1-01 golden lesson.
-- Public runtime data is explicitly granted and protected by RLS. Private answers remain private.

create table public.lesson_audio_segments (
  id bigint generated by default as identity primary key,
  lesson_block_id bigint not null references public.lesson_blocks(id) on delete cascade,
  external_id text not null unique,
  item_key text not null,
  segment_kind text not null check (segment_kind in ('term', 'example', 'pronunciation', 'listening', 'speaking')),
  position integer not null check (position > 0),
  speech_text text not null check (length(trim(speech_text)) > 0),
  normalized_text text not null check (length(trim(normalized_text)) > 0),
  audio_path text,
  slow_audio_path text,
  audio_status text not null default 'missing' check (audio_status in ('missing', 'generating', 'ready', 'failed')),
  audio_text_hash text,
  audio_voice text,
  audio_locale text,
  audio_generated_at timestamptz,
  audio_generation_started_at timestamptz,
  audio_error text,
  tts_config jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  unique (lesson_block_id, item_key, segment_kind)
);
create index lesson_audio_segments_block_idx on public.lesson_audio_segments (lesson_block_id, position);
create index lesson_audio_segments_status_idx on public.lesson_audio_segments (audio_status, lesson_block_id);

create table public.exercise_assistance (
  student_id uuid not null references public.profiles(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  hint_used boolean not null default false,
  answer_revealed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (student_id, exercise_id)
);

create table public.lesson_can_do_checks (
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  item_key text not null,
  checked boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (student_id, lesson_id, item_key)
);

alter table public.lesson_audio_segments enable row level security;
alter table public.exercise_assistance enable row level security;
alter table public.lesson_can_do_checks enable row level security;

create policy "accessible lesson audio segments"
  on public.lesson_audio_segments for select to authenticated
  using (exists (
    select 1 from public.lesson_blocks b
    where b.id = lesson_block_id and private.can_access_lesson(b.lesson_id)
  ));
create policy "assistance read self or admin"
  on public.exercise_assistance for select to authenticated
  using ((select auth.uid()) = student_id or private.is_admin());
create policy "can do checks read self or admin"
  on public.lesson_can_do_checks for select to authenticated
  using ((select auth.uid()) = student_id or private.is_admin());

revoke all on public.lesson_audio_segments, public.exercise_assistance,
  public.lesson_can_do_checks from public, anon, authenticated;
grant select on public.lesson_audio_segments, public.exercise_assistance,
  public.lesson_can_do_checks to authenticated;
grant all on public.lesson_audio_segments, public.exercise_assistance,
  public.lesson_can_do_checks to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.mark_exercise_hint_used(p_exercise_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare target_lesson_id bigint;
begin
  select b.lesson_id into target_lesson_id
  from public.exercises e join public.lesson_blocks b on b.id = e.lesson_block_id
  where e.id = p_exercise_id;
  if (select auth.uid()) is null or target_lesson_id is null
    or not private.can_access_lesson(target_lesson_id) then
    raise exception 'exercise_not_accessible' using errcode = '42501';
  end if;
  insert into public.exercise_assistance (student_id, exercise_id, hint_used, updated_at)
  values ((select auth.uid()), p_exercise_id, true, now())
  on conflict (student_id, exercise_id) do update
    set hint_used = true, updated_at = now();
end;
$$;

create or replace function public.reveal_exercise_answer(p_exercise_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_lesson_id bigint;
  exercise_external_id text;
  expected jsonb;
  accepted jsonb;
  model text;
  reason text;
  mode text;
  safe_answer jsonb;
begin
  select b.lesson_id, e.external_id, e.grading_mode
  into target_lesson_id, exercise_external_id, mode
  from public.exercises e join public.lesson_blocks b on b.id = e.lesson_block_id
  where e.id = p_exercise_id;
  if (select auth.uid()) is null or target_lesson_id is null
    or not private.can_access_lesson(target_lesson_id) then
    raise exception 'exercise_not_accessible' using errcode = '42501';
  end if;
  if not exists (
    select 1 from public.exercise_attempts a
    where a.student_id = (select auth.uid()) and a.exercise_id = p_exercise_id
  ) then
    raise exception 'attempt_required_before_reveal' using errcode = 'P0001';
  end if;

  select k.expected_answer, k.accepted_answers, k.model_answer, k.rationale
  into expected, accepted, model, reason
  from private.answer_keys k where k.external_id = exercise_external_id;
  if expected is null and coalesce(jsonb_array_length(coalesce(accepted, '[]'::jsonb)), 0) = 0
    and nullif(model, '') is null then
    raise exception 'answer_key_missing' using errcode = 'P0002';
  end if;
  safe_answer := case
    when mode = 'subjective' and nullif(model, '') is not null then to_jsonb(model)
    when expected is not null then expected
    else accepted -> 0
  end;

  insert into public.exercise_assistance (student_id, exercise_id, answer_revealed, updated_at)
  values ((select auth.uid()), p_exercise_id, true, now())
  on conflict (student_id, exercise_id) do update
    set answer_revealed = true, updated_at = now();
  return jsonb_build_object(
    'answer', safe_answer,
    'explanation', coalesce(reason, 'Compare com sua resposta e tente novamente.'),
    'assisted', true
  );
end;
$$;

create or replace function public.set_lesson_can_do_check(
  p_lesson_id bigint,
  p_item_key text,
  p_checked boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not private.can_access_lesson(p_lesson_id)
    or nullif(trim(p_item_key), '') is null then
    raise exception 'lesson_not_accessible' using errcode = '42501';
  end if;
  insert into public.lesson_can_do_checks (student_id, lesson_id, item_key, checked, updated_at)
  values ((select auth.uid()), p_lesson_id, p_item_key, p_checked, now())
  on conflict (student_id, lesson_id, item_key) do update
    set checked = excluded.checked, updated_at = now();
end;
$$;

create or replace function public.claim_lesson_audio_segment_generation(
  p_segment_id bigint,
  p_text_hash text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare claimed boolean := false;
begin
  if not private.is_admin() then raise exception 'admin_required' using errcode = '42501'; end if;
  update public.lesson_audio_segments set
    audio_status = 'generating', audio_generation_started_at = now(),
    audio_text_hash = p_text_hash, audio_error = null
  where id = p_segment_id and (
    audio_status in ('missing', 'failed')
    or audio_text_hash is distinct from p_text_hash
    or audio_generation_started_at < now() - interval '10 minutes'
  );
  claimed := found;
  return claimed;
end;
$$;

create or replace function public.get_lesson_detail(p_lesson_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  if (select auth.uid()) is null or not private.can_access_lesson(p_lesson_id) then
    raise exception 'lesson_not_accessible' using errcode = '42501';
  end if;
  select jsonb_build_object(
    'id', l.id, 'external_id', l.external_id, 'level_code', m.level_code,
    'level_lesson_number', l.level_lesson_number, 'module_id', m.id,
    'module_external_id', m.external_id, 'module_title', m.title,
    'module_position', m.position, 'module_lesson_number', l.module_lesson_number,
    'global_order', l.global_order, 'title', l.title, 'summary', l.summary,
    'xp_reward', l.xp_reward, 'is_checkpoint', l.is_checkpoint,
    'can_do', l.can_do, 'metadata', l.metadata, 'content_version', l.course_version,
    'can_do_checks', coalesce((select jsonb_object_agg(c.item_key, c.checked)
      from public.lesson_can_do_checks c where c.student_id = (select auth.uid())
      and c.lesson_id = l.id), '{}'::jsonb),
    'saved_position', coalesce((select p.current_position from public.lesson_progress p
      where p.student_id = (select auth.uid()) and p.lesson_id = l.id), 0),
    'blocks', coalesce((select jsonb_agg(jsonb_build_object(
      'id', b.id, 'external_id', b.external_id, 'block_type', b.block_type,
      'position', b.position, 'title', b.title, 'content', b.content,
      'audio_path', b.audio_path, 'slow_audio_path', b.slow_audio_path,
      'audio_status', b.audio_status, 'audio_required', b.audio_required,
      'audio_role', b.audio_role, 'transcript', b.transcript,
      'audio_segments', coalesce((select jsonb_agg(jsonb_build_object(
        'id', s.id, 'external_id', s.external_id, 'item_key', s.item_key,
        'segment_kind', s.segment_kind, 'position', s.position,
        'speech_text', s.speech_text, 'status', s.audio_status
      ) order by s.position, s.id) from public.lesson_audio_segments s
      where s.lesson_block_id = b.id), '[]'::jsonb),
      'exercise', case when e.id is null then null else jsonb_build_object(
        'id', e.id, 'external_id', e.external_id, 'exercise_type', e.exercise_type,
        'prompt', e.prompt, 'instruction', e.instruction, 'content', e.content,
        'feedback_correct', e.feedback_correct, 'feedback_incorrect', e.feedback_incorrect,
        'grading_mode', e.grading_mode,
        'assistance', coalesce((select jsonb_build_object(
          'hint_used', a.hint_used, 'answer_revealed', a.answer_revealed
        ) from public.exercise_assistance a where a.student_id = (select auth.uid())
          and a.exercise_id = e.id), jsonb_build_object('hint_used', false, 'answer_revealed', false)),
        'options', coalesce((select jsonb_agg(jsonb_build_object(
          'id', o.id, 'label', o.label, 'value', o.value, 'position', o.position
        ) order by o.position) from public.exercise_options o where o.exercise_id = e.id), '[]'::jsonb)
      ) end
    ) order by b.position)
    from public.lesson_blocks b left join public.exercises e on e.lesson_block_id = b.id
    where b.lesson_id = l.id), '[]'::jsonb)
  ) into result
  from public.lessons l join public.modules m on m.id = l.module_id
  where l.id = p_lesson_id and l.published and not l.is_legacy;
  if result is null then raise exception 'lesson_not_found' using errcode = 'P0002'; end if;
  return result;
end;
$$;

create or replace function public.complete_lesson(p_lesson_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  total_exercises integer; submitted_exercises integer; graded_exercises integer;
  correct_answers integer; score_percent integer; reward integer; checkpoint boolean;
  next_lesson_id bigint; current_order integer; next_level text; awarded integer := 0;
  assisted boolean := false;
begin
  if not private.can_access_lesson(p_lesson_id) then raise exception 'lesson_not_accessible' using errcode = '42501'; end if;
  select l.xp_reward, l.is_checkpoint, l.global_order into reward, checkpoint, current_order
  from public.lessons l where l.id = p_lesson_id and l.published and not l.is_legacy;
  if current_order is null then raise exception 'lesson_not_found' using errcode = 'P0002'; end if;
  select count(*)::integer, count(*) filter (where e.grading_mode = 'automatic')::integer
  into total_exercises, graded_exercises from public.exercises e
  join public.lesson_blocks b on b.id = e.lesson_block_id where b.lesson_id = p_lesson_id;
  select count(*)::integer into submitted_exercises from (
    select distinct a.exercise_id from public.exercise_attempts a
    join public.exercises e on e.id = a.exercise_id join public.lesson_blocks b on b.id = e.lesson_block_id
    where a.student_id = (select auth.uid()) and b.lesson_id = p_lesson_id
  ) submitted;
  if submitted_exercises < total_exercises then raise exception 'lesson_exercises_incomplete' using errcode = 'P0001'; end if;
  select count(*)::integer into correct_answers from (
    select distinct a.exercise_id from public.exercise_attempts a
    join public.exercises e on e.id = a.exercise_id join public.lesson_blocks b on b.id = e.lesson_block_id
    where a.student_id = (select auth.uid()) and b.lesson_id = p_lesson_id
      and e.grading_mode = 'automatic' and a.correct
  ) correct;
  select exists (
    select 1 from public.exercise_assistance a join public.exercises e on e.id = a.exercise_id
    join public.lesson_blocks b on b.id = e.lesson_block_id
    where a.student_id = (select auth.uid()) and b.lesson_id = p_lesson_id
      and (a.hint_used or a.answer_revealed)
  ) into assisted;
  score_percent := case when graded_exercises = 0 then 100
    else round((correct_answers::numeric / graded_exercises) * 100)::integer end;
  reward := reward
    + case when not assisted and graded_exercises > 0 and correct_answers = graded_exercises then 20 else 0 end
    + case when checkpoint then 50 else 0 end;
  insert into public.lesson_progress
    (student_id, lesson_id, status, current_position, score_percent, started_at, completed_at, updated_at)
  values ((select auth.uid()), p_lesson_id, 'completed', 0, score_percent, now(), now(), now())
  on conflict (student_id, lesson_id) do update set status = 'completed',
    score_percent = greatest(coalesce(public.lesson_progress.score_percent, 0), excluded.score_percent),
    completed_at = coalesce(public.lesson_progress.completed_at, now()), updated_at = now();
  insert into public.xp_events (student_id, points, event_type, source_id)
  values ((select auth.uid()), reward, 'lesson_completed', p_lesson_id)
  on conflict (student_id, event_type, source_id) where source_id is not null do nothing;
  if found then awarded := reward; end if;
  insert into public.review_schedule (student_id, lesson_id, review_offset_days, due_at)
  select (select auth.uid()), p_lesson_id, days, now() + make_interval(days => days)
  from unnest(array[1,3,7,21]) days on conflict (student_id, lesson_id, review_offset_days) do nothing;
  select l.id, m.level_code into next_lesson_id, next_level from public.lessons l
  join public.modules m on m.id = l.module_id where l.published and not l.is_legacy
    and l.global_order > current_order order by l.global_order limit 1;
  if next_lesson_id is not null then
    insert into public.student_lesson_access (student_id, lesson_id, unlocked)
    values ((select auth.uid()), next_lesson_id, true)
    on conflict (student_id, lesson_id) do update set unlocked = true, unlocked_at = now();
    update public.profiles set current_level_code = next_level, updated_at = now() where id = (select auth.uid());
  else
    update public.profiles set course_completed_at = coalesce(course_completed_at, now()), updated_at = now()
    where id = (select auth.uid());
  end if;
  return jsonb_build_object('correct_answers', correct_answers, 'total_exercises', graded_exercises,
    'submitted_exercises', submitted_exercises, 'score_percent', score_percent,
    'xp_awarded', awarded, 'next_lesson_id', next_lesson_id,
    'course_completed', next_lesson_id is null, 'assisted', assisted);
end;
$$;

revoke all on function public.mark_exercise_hint_used(bigint), public.reveal_exercise_answer(bigint),
  public.set_lesson_can_do_check(bigint, text, boolean),
  public.claim_lesson_audio_segment_generation(bigint, text) from public, anon, authenticated;
grant execute on function public.mark_exercise_hint_used(bigint), public.reveal_exercise_answer(bigint),
  public.set_lesson_can_do_check(bigint, text, boolean) to authenticated;
grant execute on function public.mark_exercise_hint_used(bigint), public.reveal_exercise_answer(bigint),
  public.set_lesson_can_do_check(bigint, text, boolean),
  public.claim_lesson_audio_segment_generation(bigint, text) to service_role;
revoke all on function public.get_lesson_detail(bigint), public.complete_lesson(bigint) from public, anon;
grant execute on function public.get_lesson_detail(bigint), public.complete_lesson(bigint) to authenticated, service_role;
